server:
  port: 8084
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:mysql://\:3306/finflow_document?createDatabaseIfNotExist=true
    username: root
    password: Durga@123
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  exchange: loan.exchange
  routing:
    key:
      uploaded: document.uploaded.routing.key

springdoc:
  api-docs:
    path: /api/v1/documents/v3/api-docs
