CREATE DATABASE IF NOT EXISTS finflow_application;
CREATE DATABASE IF NOT EXISTS finflow_document;
CREATE DATABASE IF NOT EXISTS finflow_admin;
CREATE DATABASE IF NOT EXISTS finflow_auth;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
